'use client';
import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import {MultiFormatReader,BarcodeFormat,DecodeHintType,BinaryBitmap,HybridBinarizer,HTMLCanvasElementLuminanceSource} from '@zxing/library';
export function assetLink(id:string){return window.location.origin+'/?asset='+encodeURIComponent(id)}
export function readAsset(value:string){try{const u=new URL(value);if(u.origin!==window.location.origin)return null;const id=u.searchParams.get('asset');return id&&/^[-A-Za-z0-9_]{1,60}$/.test(id)?id:null}catch{return /^[-A-Za-z0-9_]{1,60}$/.test(value)?value:null}}
export function QRLabel({id,category}:{id:string;category:string}){const [src,setSrc]=useState('');useEffect(()=>{let active=true;QRCode.toDataURL(assetLink(id),{width:320,margin:4,errorCorrectionLevel:'M'}).then(s=>{if(active)setSrc(s)});return()=>{active=false}},[id]);return <div className="qrlabel"><img className="qrbrand" src="/dental-stars-logo.png" alt="Dental Stars" width="278" height="62"/>{src?<img src={src} alt={'QR code for '+id}/>:<p>Preparing QR…</p>}<strong>{id}</strong><small>{category}</small><small>PROPERTY OF DENTAL STARS</small></div>}
export function Scanner({onScan,onClose}:{onScan:(id:string)=>void;onClose:()=>void}){const video=useRef<HTMLVideoElement>(null);const [error,setError]=useState('');useEffect(()=>{let active=true,stream:MediaStream|undefined,frame=0;const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d',{willReadFrequently:true});const reader=new MultiFormatReader();reader.setHints(new Map([[DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.CODE_128,BarcodeFormat.CODE_39,BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.ITF,BarcodeFormat.CODABAR]]]));let lastDecode=0;async function start(){try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera unavailable. Open this app in your phone browser, or use a USB/Bluetooth scanner in the asset ID field.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!active){stream.getTracks().forEach(t=>t.stop());return}if(video.current){video.current.srcObject=stream;await video.current.play()}const tick=()=>{if(!active)return;const v=video.current;const now=performance.now();if(v&&v.readyState>=2&&ctx&&now-lastDecode>180){lastDecode=now;canvas.width=Math.min(v.videoWidth,1280);canvas.height=Math.round(v.videoHeight*canvas.width/v.videoWidth);ctx.drawImage(v,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height);const qr=jsQR(data.data,data.width,data.height,{inversionAttempts:'dontInvert'});let value=qr?.data; if(!value){try{value=reader.decodeWithState(new BinaryBitmap(new HybridBinarizer(new HTMLCanvasElementLuminanceSource(canvas)))).getText()}catch{}}if(value){const id=readAsset(value);if(id){active=false;stream?.getTracks().forEach(t=>t.stop());onScan(id);return}else setError('Unsupported code content. Use a unique asset ID (letters, numbers, hyphens or underscores), or a Dental Stars QR link.')}}frame=requestAnimationFrame(tick)};tick()}catch(e:any){setError(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser settings, or use a USB/Bluetooth scanner in the asset ID field.':e.message)}}start();return()=>{active=false;cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop())}},[]);return <div className="overlay"><div className="modal scanner" role="dialog" aria-modal="true" aria-label="Scan QR or barcode"><h2>Scan QR or barcode</h2><p>Point your camera at a QR code or barcode. Keep the entire code visible in good light. New IDs open a registration form; existing IDs open their records.</p><video ref={video} muted playsInline/>{error&&<p className="error" role="alert">{error}</p>}<button className="secondary" onClick={onClose}>Close scanner</button></div></div>}
